name: CI/CD Workflow

on:

push:

branches:

- main

jobs:

  build:

    runs-on: ubuntu-latest

    name: Build and Test

    steps:

    - uses: actions/checkout@v3

    - uses: bahmutov/npm-install@v1

    - run: npm run lint (Run ESLint)

    - run: npm run test (Run Jest)
